// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Ben struct {
	ID        uuid.UUID
	Nome      string
	Status    sql.NullString
	Tipo      string
	SetorID   sql.NullInt32
	CreatedAt sql.NullTime
}

type Fabricante struct {
	ID        int32
	Nome      string
	Cnpj      string
	CreatedAt sql.NullTime
}

type Fornecedore struct {
	ID        int32
	Nome      string
	Cnpj      string
	Contato   string
	CreatedAt sql.NullTime
}

type Setore struct {
	ID        int32
	Nome      string
	Local     string
	CreatedAt sql.NullTime
}

type User struct {
	ID        int32
	Nome      string
	Email     string
	Cpf       string
	Password  string
	CreatedAt sql.NullTime
}
