// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, email, cpf, password)
VALUES ($1, $2, $3, $4)
RETURNING id, nome, email, cpf, password, created_at
`

type CreateUserParams struct {
	Nome     string
	Email    string
	Cpf      string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.Email,
		arg.Cpf,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, nome, email, cpf, password, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, email, cpf, password, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, nome, email, cpf, password, created_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Cpf,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET nome = $1, email = $2, cpf = $3
WHERE id = $4
RETURNING id, nome, email, cpf, password, created_at
`

type UpdateUserParams struct {
	Nome  string
	Email string
	Cpf   string
	ID    int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Nome,
		arg.Email,
		arg.Cpf,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
