// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBem = `-- name: CreateBem :one
INSERT INTO bens (id, nome, status, tipo, setor_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nome, status, tipo, setor_id, created_at
`

type CreateBemParams struct {
	ID      uuid.UUID
	Nome    string
	Status  sql.NullString
	Tipo    string
	SetorID sql.NullInt32
}

func (q *Queries) CreateBem(ctx context.Context, arg CreateBemParams) (Ben, error) {
	row := q.db.QueryRowContext(ctx, createBem,
		arg.ID,
		arg.Nome,
		arg.Status,
		arg.Tipo,
		arg.SetorID,
	)
	var i Ben
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Status,
		&i.Tipo,
		&i.SetorID,
		&i.CreatedAt,
	)
	return i, err
}

const createFabricante = `-- name: CreateFabricante :one

INSERT INTO fabricantes (nome, cnpj)
VALUES ($1, $2)
RETURNING id, nome, cnpj, created_at
`

type CreateFabricanteParams struct {
	Nome string
	Cnpj string
}

// FABRICANTES
func (q *Queries) CreateFabricante(ctx context.Context, arg CreateFabricanteParams) (Fabricante, error) {
	row := q.db.QueryRowContext(ctx, createFabricante, arg.Nome, arg.Cnpj)
	var i Fabricante
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cnpj,
		&i.CreatedAt,
	)
	return i, err
}

const createFornecedor = `-- name: CreateFornecedor :one

INSERT INTO fornecedores (nome, cnpj, contato)
VALUES ($1, $2, $3)
RETURNING id, nome, cnpj, contato, created_at
`

type CreateFornecedorParams struct {
	Nome    string
	Cnpj    string
	Contato string
}

// FORNECEDORES
func (q *Queries) CreateFornecedor(ctx context.Context, arg CreateFornecedorParams) (Fornecedore, error) {
	row := q.db.QueryRowContext(ctx, createFornecedor, arg.Nome, arg.Cnpj, arg.Contato)
	var i Fornecedore
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cnpj,
		&i.Contato,
		&i.CreatedAt,
	)
	return i, err
}

const createSetor = `-- name: CreateSetor :one
INSERT INTO setores (nome, local)
VALUES ($1, $2)
RETURNING id, nome, local, created_at
`

type CreateSetorParams struct {
	Nome  string
	Local string
}

func (q *Queries) CreateSetor(ctx context.Context, arg CreateSetorParams) (Setore, error) {
	row := q.db.QueryRowContext(ctx, createSetor, arg.Nome, arg.Local)
	var i Setore
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Local,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, email, cpf, password)
VALUES ($1, $2, $3, $4)
RETURNING id, nome, email, cpf, password, created_at
`

type CreateUserParams struct {
	Nome     string
	Email    string
	Cpf      string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.Email,
		arg.Cpf,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBem = `-- name: DeleteBem :exec
DELETE FROM bens
WHERE id = $1
`

func (q *Queries) DeleteBem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBem, id)
	return err
}

const deleteFabricante = `-- name: DeleteFabricante :exec
DELETE FROM fabricantes
WHERE id = $1
`

func (q *Queries) DeleteFabricante(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFabricante, id)
	return err
}

const deleteFornecedor = `-- name: DeleteFornecedor :exec
DELETE FROM fornecedores
WHERE id = $1
`

func (q *Queries) DeleteFornecedor(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteFornecedor, id)
	return err
}

const deleteSetor = `-- name: DeleteSetor :exec
DELETE FROM setores
WHERE id = $1
`

func (q *Queries) DeleteSetor(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSetor, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getBemByID = `-- name: GetBemByID :one
SELECT id, nome, status, tipo, setor_id, created_at FROM bens
WHERE id = $1
`

func (q *Queries) GetBemByID(ctx context.Context, id uuid.UUID) (Ben, error) {
	row := q.db.QueryRowContext(ctx, getBemByID, id)
	var i Ben
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Status,
		&i.Tipo,
		&i.SetorID,
		&i.CreatedAt,
	)
	return i, err
}

const getFabricanteByID = `-- name: GetFabricanteByID :one
SELECT id, nome, cnpj, created_at FROM fabricantes
WHERE id = $1
`

func (q *Queries) GetFabricanteByID(ctx context.Context, id int32) (Fabricante, error) {
	row := q.db.QueryRowContext(ctx, getFabricanteByID, id)
	var i Fabricante
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cnpj,
		&i.CreatedAt,
	)
	return i, err
}

const getFornecedorByID = `-- name: GetFornecedorByID :one
SELECT id, nome, cnpj, contato, created_at
FROM fornecedores
WHERE id = $1
`

func (q *Queries) GetFornecedorByID(ctx context.Context, id int32) (Fornecedore, error) {
	row := q.db.QueryRowContext(ctx, getFornecedorByID, id)
	var i Fornecedore
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cnpj,
		&i.Contato,
		&i.CreatedAt,
	)
	return i, err
}

const getSetorByID = `-- name: GetSetorByID :one
SELECT id, nome, local, created_at FROM setores
WHERE id = $1
`

func (q *Queries) GetSetorByID(ctx context.Context, id int32) (Setore, error) {
	row := q.db.QueryRowContext(ctx, getSetorByID, id)
	var i Setore
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Local,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, nome, email, cpf, password, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, email, cpf, password, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listBens = `-- name: ListBens :many
SELECT id, nome, status, tipo, setor_id, created_at FROM bens
`

func (q *Queries) ListBens(ctx context.Context) ([]Ben, error) {
	rows, err := q.db.QueryContext(ctx, listBens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ben
	for rows.Next() {
		var i Ben
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Status,
			&i.Tipo,
			&i.SetorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFornecedores = `-- name: ListFornecedores :many
SELECT id, nome, cnpj, contato, created_at
FROM fornecedores
`

func (q *Queries) ListFornecedores(ctx context.Context) ([]Fornecedore, error) {
	rows, err := q.db.QueryContext(ctx, listFornecedores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fornecedore
	for rows.Next() {
		var i Fornecedore
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Cnpj,
			&i.Contato,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetores = `-- name: ListSetores :many
SELECT id, nome, local, created_at FROM setores
`

func (q *Queries) ListSetores(ctx context.Context) ([]Setore, error) {
	rows, err := q.db.QueryContext(ctx, listSetores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setore
	for rows.Next() {
		var i Setore
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Local,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, nome, email, cpf, password, created_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.Cpf,
			&i.Password,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBem = `-- name: UpdateBem :one
UPDATE bens
SET nome = $1, status = $2, tipo = $3, setor_id = $4
WHERE id = $5
RETURNING id, nome, status, tipo, setor_id, created_at
`

type UpdateBemParams struct {
	Nome    string
	Status  sql.NullString
	Tipo    string
	SetorID sql.NullInt32
	ID      uuid.UUID
}

func (q *Queries) UpdateBem(ctx context.Context, arg UpdateBemParams) (Ben, error) {
	row := q.db.QueryRowContext(ctx, updateBem,
		arg.Nome,
		arg.Status,
		arg.Tipo,
		arg.SetorID,
		arg.ID,
	)
	var i Ben
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Status,
		&i.Tipo,
		&i.SetorID,
		&i.CreatedAt,
	)
	return i, err
}

const updateFabricante = `-- name: UpdateFabricante :one
UPDATE fabricantes
SET nome = $1, cnpj = $2
WHERE id = $3
RETURNING id, nome, cnpj, created_at
`

type UpdateFabricanteParams struct {
	Nome string
	Cnpj string
	ID   int32
}

func (q *Queries) UpdateFabricante(ctx context.Context, arg UpdateFabricanteParams) (Fabricante, error) {
	row := q.db.QueryRowContext(ctx, updateFabricante, arg.Nome, arg.Cnpj, arg.ID)
	var i Fabricante
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cnpj,
		&i.CreatedAt,
	)
	return i, err
}

const updateFornecedor = `-- name: UpdateFornecedor :one
UPDATE fornecedores
SET nome = $1,
    cnpj = $2,
    contato = $3
WHERE id = $4
RETURNING id, nome, cnpj, contato, created_at
`

type UpdateFornecedorParams struct {
	Nome    string
	Cnpj    string
	Contato string
	ID      int32
}

func (q *Queries) UpdateFornecedor(ctx context.Context, arg UpdateFornecedorParams) (Fornecedore, error) {
	row := q.db.QueryRowContext(ctx, updateFornecedor,
		arg.Nome,
		arg.Cnpj,
		arg.Contato,
		arg.ID,
	)
	var i Fornecedore
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Cnpj,
		&i.Contato,
		&i.CreatedAt,
	)
	return i, err
}

const updateSetor = `-- name: UpdateSetor :one
UPDATE setores
SET nome = $1, local = $2
WHERE id = $3
RETURNING id, nome, local, created_at
`

type UpdateSetorParams struct {
	Nome  string
	Local string
	ID    int32
}

func (q *Queries) UpdateSetor(ctx context.Context, arg UpdateSetorParams) (Setore, error) {
	row := q.db.QueryRowContext(ctx, updateSetor, arg.Nome, arg.Local, arg.ID)
	var i Setore
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Local,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET nome = $1, email = $2, cpf = $3
WHERE id = $4
RETURNING id, nome, email, cpf, password, created_at
`

type UpdateUserParams struct {
	Nome  string
	Email string
	Cpf   string
	ID    int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Nome,
		arg.Email,
		arg.Cpf,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.Cpf,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
