// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBem(ctx context.Context, arg CreateBemParams) (Ben, error)
	// FABRICANTES
	CreateFabricante(ctx context.Context, arg CreateFabricanteParams) (Fabricante, error)
	// FORNECEDORES
	CreateFornecedor(ctx context.Context, arg CreateFornecedorParams) (Fornecedore, error)
	CreateSetor(ctx context.Context, arg CreateSetorParams) (Setore, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBem(ctx context.Context, id uuid.UUID) error
	DeleteFabricante(ctx context.Context, id int32) error
	DeleteFornecedor(ctx context.Context, id int32) error
	DeleteSetor(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetBemByID(ctx context.Context, id uuid.UUID) (Ben, error)
	GetFabricanteByCnpj(ctx context.Context, cnpj string) (Fabricante, error)
	GetFabricanteByID(ctx context.Context, id int32) (Fabricante, error)
	GetFornecedorByCnpj(ctx context.Context, cnpj string) (Fornecedore, error)
	GetFornecedorByID(ctx context.Context, id int32) (Fornecedore, error)
	GetSetorByID(ctx context.Context, id int32) (Setore, error)
	GetSetorByNome(ctx context.Context, nome string) (Setore, error)
	GetUserByCpf(ctx context.Context, cpf string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListBens(ctx context.Context) ([]Ben, error)
	ListFabricantes(ctx context.Context) ([]Fabricante, error)
	ListFornecedores(ctx context.Context) ([]Fornecedore, error)
	ListSetores(ctx context.Context) ([]Setore, error)
	ListSetoresWithBens(ctx context.Context) ([]ListSetoresWithBensRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateBem(ctx context.Context, arg UpdateBemParams) (Ben, error)
	UpdateFabricante(ctx context.Context, arg UpdateFabricanteParams) (Fabricante, error)
	UpdateFornecedor(ctx context.Context, arg UpdateFornecedorParams) (Fornecedore, error)
	UpdateSetor(ctx context.Context, arg UpdateSetorParams) (Setore, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
